//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.03 at 09:36:36 AM CET 
//


package com.realdolmen.rdfleet.web_services;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.realdolmen.rdfleet.web_services package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.realdolmen.rdfleet.web_services
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MileageUpdateResponse }
     * 
     */
    public MileageUpdateResponse createMileageUpdateResponse() {
        return new MileageUpdateResponse();
    }

    /**
     * Create an instance of {@link MileageUpdateRequest }
     * 
     */
    public MileageUpdateRequest createMileageUpdateRequest() {
        return new MileageUpdateRequest();
    }

    /**
     * Create an instance of {@link MileageUpdateObject }
     * 
     */
    public MileageUpdateObject createMileageUpdateObject() {
        return new MileageUpdateObject();
    }

}
