//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.10 at 04:19:09 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://rdfleet.realdolmen.com/web-services", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.realdolmen.rdfleet.web_services;
